name: it_book
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  http: ^0.13.5
  get: ^4.6.5
  flutter_barcode_scanner: ^2.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  flutter_html: ^2.1.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  image_picker: ^0.8.9
  multi_image_picker_view: ^0.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cat.png
    - assets/doit.png
    - assets/tino.png
    - assets/swift.png
    - assets/user.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
